export const starterDeckIds = [
  "shonen-g0-spark",
  "spirit-g0-heal",
  "mecha-g0-front",
  "stage-g0-crit",
  "shonen-g1-boost",
  "shonen-g1-boost",
  "spirit-g1-lantern",
  "shadow-g1-guard",
  "shonen-g2-striker",
  "shonen-g2-striker",
  "shonen-g3-astral",
  "mecha-g3-railgun",
  "stage-g3-duet",
  "shadow-g3-eclipse",
];

export const cards = [
  {
    id: "shonen-g0-spark",
    name: "Spark Cadet Riku",
    anime: "Starblade Academy",
    nation: "Shonen Nova",
    grade: 0,
    power: 6000,
    shield: 5000,
    critical: 1,
    rarity: "C",
    trigger: "draw",
    art: "assets/cards/astral-hero.svg",
    attackAnimation: "slash",
    skills: [{ name: "Draw Trigger", timing: "driveCheck", engineEffect: "draw", amount: 1 }],
  },
  {
    id: "shonen-g1-boost",
    name: "Blaze Senpai Kana",
    anime: "Starblade Academy",
    nation: "Shonen Nova",
    grade: 1,
    power: 8000,
    shield: 5000,
    critical: 1,
    rarity: "R",
    art: "assets/cards/astral-hero.svg",
    attackAnimation: "impact",
    skills: [{ name: "Battle Cheer", timing: "boost", engineEffect: "gainPower", amount: 3000 }],
  },
  {
    id: "shonen-g2-striker",
    name: "Meteor Striker Juno",
    anime: "Starblade Academy",
    nation: "Shonen Nova",
    grade: 2,
    power: 10000,
    shield: 5000,
    critical: 1,
    rarity: "RR",
    art: "assets/cards/astral-hero.svg",
    attackAnimation: "slash",
    skills: [{ name: "Meteor Rush", timing: "attack", engineEffect: "gainPower", amount: 5000 }],
  },
  {
    id: "shonen-g3-astral",
    name: "Astral Hero, Leonis Rex",
    anime: "Starblade Academy",
    nation: "Shonen Nova",
    grade: 3,
    power: 13000,
    shield: 0,
    critical: 1,
    rarity: "SSR",
    art: "assets/cards/astral-hero.svg",
    cutscene: "assets/cutscenes/rare-hero-burst.mp4",
    attackAnimation: "beam",
    skills: [
      { name: "Heroic Arrival", timing: "onRide", engineEffect: "draw", amount: 1 },
      { name: "Final Nova Drive", timing: "attack", engineEffect: "extraCritical", amount: 1 },
    ],
  },
  {
    id: "spirit-g0-heal",
    name: "Temple Mender Yua",
    anime: "Fox Moon Pact",
    nation: "Spirit Court",
    grade: 0,
    power: 5000,
    shield: 15000,
    critical: 1,
    rarity: "C",
    trigger: "heal",
    art: "assets/cards/spirit-kitsune.svg",
    skills: [{ name: "Heal Trigger", timing: "damageCheck", engineEffect: "healOne", amount: 1 }],
  },
  {
    id: "spirit-g1-lantern",
    name: "Lantern Fox Kohaku",
    anime: "Fox Moon Pact",
    nation: "Spirit Court",
    grade: 1,
    power: 8000,
    shield: 5000,
    critical: 1,
    rarity: "R",
    art: "assets/cards/spirit-kitsune.svg",
    attackAnimation: "stage",
    skills: [{ name: "Moonlit Path", timing: "onCall", engineEffect: "soulCharge", amount: 1 }],
  },
  {
    id: "mecha-g0-front",
    name: "Orbit Drone N-00",
    anime: "Neon Armored Rail",
    nation: "Mecha Orbit",
    grade: 0,
    power: 6000,
    shield: 15000,
    critical: 1,
    rarity: "C",
    trigger: "front",
    art: "assets/cards/mecha-orbit.svg",
    skills: [{ name: "Front Trigger", timing: "driveCheck", engineEffect: "gainPower", amount: 10000 }],
  },
  {
    id: "mecha-g3-railgun",
    name: "Railgun Empress Vesta",
    anime: "Neon Armored Rail",
    nation: "Mecha Orbit",
    grade: 3,
    power: 13000,
    shield: 0,
    critical: 1,
    rarity: "SR",
    art: "assets/cards/mecha-orbit.svg",
    cutscene: "assets/cutscenes/rare-orbit-lock.mp4",
    attackAnimation: "beam",
    skills: [{ name: "Satellite Verdict", timing: "attack", engineEffect: "gainPower", amount: 5000 }],
  },
  {
    id: "stage-g0-crit",
    name: "Opening Act Miri",
    anime: "Miracle Idol Circuit",
    nation: "Mystic Stage",
    grade: 0,
    power: 5000,
    shield: 15000,
    critical: 1,
    rarity: "C",
    trigger: "critical",
    art: "assets/cards/mystic-stage.svg",
    skills: [{ name: "Critical Trigger", timing: "driveCheck", engineEffect: "extraCritical", amount: 1 }],
  },
  {
    id: "stage-g3-duet",
    name: "Starlight Duet Aria",
    anime: "Miracle Idol Circuit",
    nation: "Mystic Stage",
    grade: 3,
    power: 13000,
    shield: 0,
    critical: 1,
    rarity: "SSR",
    art: "assets/cards/mystic-stage.svg",
    cutscene: "assets/cutscenes/rare-stage-encore.mp4",
    attackAnimation: "stage",
    skills: [{ name: "Encore Step", timing: "attack", engineEffect: "draw", amount: 1 }],
  },
  {
    id: "shadow-g1-guard",
    name: "Oathbound Shade Ren",
    anime: "Night Contract Zero",
    nation: "Shadow Pact",
    grade: 1,
    power: 7000,
    shield: 10000,
    critical: 1,
    rarity: "R",
    art: "assets/cards/shadow-pact.svg",
    attackAnimation: "shadow",
    skills: [{ name: "Contract Guard", timing: "guardian", engineEffect: "guardBoost", amount: 5000 }],
  },
  {
    id: "shadow-g3-eclipse",
    name: "Eclipse Tyrant Noct",
    anime: "Night Contract Zero",
    nation: "Shadow Pact",
    grade: 3,
    power: 13000,
    shield: 0,
    critical: 1,
    rarity: "SSR",
    art: "assets/cards/shadow-pact.svg",
    cutscene: "assets/cutscenes/rare-shadow-sigil.mp4",
    attackAnimation: "shadow",
    skills: [{ name: "Midnight Clause", timing: "attack", engineEffect: "extraCritical", amount: 1 }],
  },
];

export const cardsById = new Map(cards.map((card) => [card.id, card]));
